environment:
  global:
    DROPBOX_TOKEN:
      secure: UO64ZwJpnDQe5c7xArS14TLnqUi7TR76tJLpZVxo5lV8GJXEkDBEOjFsmaEVFQ/rvqCmMkECYE3RNWhFO/DE0o3Vh/6FCOiO2ZAQsKkOIGk=

  matrix:
    # win builds
    - PYTHON: "C:\\Python27"
      PYTHON_ARCH: 32
      MSVC_VERSION: "Visual Studio 10"
      job_group: "windows"

    - PYTHON: "C:\\Python33"
      PYTHON_ARCH: 32
      MSVC_VERSION: "Visual Studio 10"
      job_group: "windows"

    - PYTHON: "C:\\Python34"
      PYTHON_ARCH: 32
      MSVC_VERSION: "Visual Studio 10"
      job_group: "windows"

    - PYTHON: "C:\\Python35"
      PYTHON_ARCH: 32
      MSVC_VERSION: "Visual Studio 14"
      job_group: "windows"

    - PYTHON: "C:\\Python36"
      PYTHON_ARCH: 32
      MSVC_VERSION: "Visual Studio 14"
      job_group: "windows"

    - PYTHON: "C:\\Python37"
      PYTHON_ARCH: 32
      MSVC_VERSION: "Visual Studio 14"
      job_group: "windows"

    - PYTHON: "C:\\Python38"
      PYTHON_ARCH: 32
      MSVC_VERSION: "Visual Studio 14"
      job_group: "windows"

    - PYTHON: "C:\\Python39"
      PYTHON_ARCH: 32
      MSVC_VERSION: "Visual Studio 18"
      appveyor_build_worker_image: Visual Studio 2019
      job_group: "windows"


    # x64 builds
    - PYTHON: "C:\\Python27-x64"
      PYTHON_ARCH: 64
      MSVC_VERSION: "Visual Studio 10 Win64"
      job_group: "windows"

    - PYTHON: "C:\\Python33-x64"
      PYTHON_ARCH: 64
      MSVC_VERSION: "Visual Studio 10 Win64"
      DISTUTILS_USE_SDK: "1"
      job_group: "windows"

    - PYTHON: "C:\\Python34-x64"
      PYTHON_ARCH: 64
      MSVC_VERSION: "Visual Studio 10 Win64"
      DISTUTILS_USE_SDK: "1"
      job_group: "windows"

    - PYTHON: "C:\\Python35-x64"
      PYTHON_ARCH: 64
      MSVC_VERSION: "Visual Studio 14 Win64"
      job_group: "windows"

    - PYTHON: "C:\\Python36-x64"
      PYTHON_ARCH: 64
      MSVC_VERSION: "Visual Studio 14 Win64"
      job_group: "windows"

    - PYTHON: "C:\\Python37-x64"
      PYTHON_ARCH: 64
      MSVC_VERSION: "Visual Studio 14 Win64"
      job_group: "windows"

    - PYTHON: "C:\\Python38-x64"
      PYTHON_ARCH: 64
      MSVC_VERSION: "Visual Studio 14 Win64"
      job_group: "windows"

    - PYTHON: "C:\\Python39-x64"
      PYTHON_ARCH: 64
      MSVC_VERSION: "Visual Studio 18 Win64"
      appveyor_build_worker_image: Visual Studio 2019
      job_group: "windows"

    # osx builds
    - PY_VERSION: 2.7
      job_group: "macos"
      appveyor_build_worker_image: macos

    - PY_VERSION: 3.4
      job_group: "macos"
      appveyor_build_worker_image: macos

    - PY_VERSION: 3.5
      job_group: "macos"
      appveyor_build_worker_image: macos

    - PY_VERSION: 3.6
      job_group: "macos"
      appveyor_build_worker_image: macos

    - PY_VERSION: 3.7
      job_group: "macos"
      appveyor_build_worker_image: macos

    - PY_VERSION: 3.8
      job_group: "macos"
      appveyor_build_worker_image: macos

    - PY_VERSION: 3.9
      job_group: "macos"
      appveyor_build_worker_image: macos


for:
  - matrix:
      only:
        - job_group: windows

    init:
      - "ECHO %PYTHON% %PYTHON_ARCH% %MSVC_VERSION%"
      - "%PYTHON%\\python.exe --version"

    install:
      # python requirements needed to create distribution
      - "%PYTHON%\\python.exe -m pip install -U wheel pip"
      # get latest version of all submodules
      - "git submodule update --init --recursive"
      - "%PYTHON%\\python.exe -m pip install -U setuptools"
      - "%PYTHON%\\python.exe -m pip install -r doc/requirements-test.txt"

    build: off

    build_script:
      - "ci\\appveyor_build.cmd %PYTHON%/python.exe -m pip wheel . -w dist"
      - "%PYTHON%/python.exe -m pip install -e ."
      - "%PYTHON%/python.exe -m pytest -v --color=yes"

  - matrix:
      only:
        - job_group: macos

    init:
      - sh: |
          source ~/venv${PY_VERSION}/bin/activate
          python --version

    install:
      # python requirements needed to create distribution
      - sh: |
          python --version
          python -m pip install -U wheel pip
          git submodule update --init --recursive
          python -m pip install -U setuptools
          python -m pip install -r doc/requirements-test.txt

    build_script:
      # todo: install from wheel to avoid double compilation
      - sh: |
          python -m pip wheel . -w dist
          ls dist
          python -m pip install -e .
          python -m pytest -v --color=yes

on_success:
  - ps: |
      if ($env:APPVEYOR_REPO_BRANCH -eq "master")
      {
         python -m pip install dropbox
         python ci/dropbox_upload.py $(python setup.py --version)
      }
      else
      {
         Write-Host "Not a master branch. Upload skipped."
      }

artifacts:
  - path: dist\*
