language: generic

env:
  global:
     - secure: BOq8PDn3iGRFfvj44kxooFvi73CdGTLWparh/hZgPZOtVpaxPgmBRdowCy8CM+Sw3UHzVx4bJtpoAVlC8HKsCHzm5RzJCPlZbLel6tFSLRpQ/P0pclbi7RJVX354xUq69hckX1NMLCzD4rrh2+nhIxN/CMW/EgaZX94+99/UUrSkyN2SnJ78+zrYRZZxtC/v1m8Q00jdS0raXYzGAh9SQuSnTf2C6nH9/oXykXmElUYGI52LoqmU3OIIWQNKNWH6vhlukuih3H5nycPm2dys8l8UxIji66pqmnyZRXsVq/5xqEYbxo493GPQQPQ2k4Zec4SOXaZ34ert4KSpK36MLSKJ59dou8+JK/yUwKeJQlHzpD5Qzwt+Je/oU3RREPzhYLc7U1QnxiNlLa4YgcCfwurFGrWmFRLe+TM2Ck6FuWi0LltGDNggFgox4I73v7odU5330qsh6Jz9aSsOsS8tc9V64jZdxiI8gK/azz0k4GI9EYpzpziFZEt3HrthVKXHrssonevUtRK8a+9Df/3cV9+KedAQarzkv7t4W61c1oA1XZHh45xUpE4x5T4mBIg+Pa+lPw748BQrLJ8zc5ZJj1g9jRGUTRlngQEy0MoWiyODzSc2VqDcLSsKbADeI73xxgq+Fxl9Dih6cKedpxpoFlxPuAD1PgvwwxitPjrnnS8=

matrix:
  include:
    - os: osx
      env: PY_VERSION=2.7

    - os: osx
      env: PY_VERSION=3.3.7

    - os: osx
      env: PY_VERSION=3.4.9

    - os: osx
      env: PY_VERSION=3.5.6

    - os: osx
      env: PY_VERSION=3.6.6

    - os: osx
      env: PY_VERSION=3.7.0

    - os: linux
      sudo: required
      dist: trusty
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
      services: docker

    - os: linux
      sudo: required
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32
      services: docker

    - os: linux
      # note: this is only to properly annotate coverage build in the matrix
      env: COVERAGE=1
      language: python
      python: '3.7'

cache:
  pip: true
  directories:
  - $HOME/.pyenv

before_install:
  - source ci/travis_before.sh

  # note: there is cython issue when python2.7 is installed using pyenv
  # note: but it is required to run everything in virtualenv
  - if [[ "$PY_VERSION" == "2.7" ]]; then pip install virtualenv; fi
  - if [[ "$PY_VERSION" == "2.7" ]]; then virtualenv build-env; fi
  - if [[ "$PY_VERSION" == "2.7" ]]; then source build-env/bin/activate; fi

install:
  # simply for logging
  - python --version
  # get all submodules (imgui-cpp)
  - git submodule update --init --recursive

script:
  - ./ci/travis_build.sh

after_success:
  # note: on certain environments there may be a problem with installing
  #       dropbox without virtualenv
  - virtualenv dist-env
  - source dist-env/bin/activate
  - python -m pip install dropbox
  # note: we upload dists only on master commits
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then python ci/dropbox_upload.py $(python setup.py --version); fi
